### ISSUE TITLE
Notice search backend

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#118]
We want to be able to search over both the preamble and the CFR changes. We need to add this functionality to -core.

**Comment by jmcarp** [comment]
Is this ready to implement? If so, I have questions, such as: is this meant for searching across proposals, within proposals, or both? Do we want to map one preamble blob (in sql) to many section-level records (in elastic) to support more granular search, or map one-to-one?

**Comment by cmc333333** [comment]
This is ready to implement; look at the existing search code CFR nodes. We'll basically just need to

1) create a row per node (as we do with the CFR data)
2) add a haystack template
3) update the search endpoint to allow searching over preambles
4) update the ui to hit that endpoint

To answer your specific questions:
> is this meant for searching across proposals, within proposals, or both

Priority is within a proposal, though it shouldn't cost much to search across proposals too.

> Do we want to map one preamble blob (in sql) to many section-level records (in elastic) to support more granular search, or map one-to-one?

Search should be per preamble node -- just duplicate the CFR search over the preamble.

**Comment by jmcarp** [comment]
To be more explicit, for the proposal we've been working with, there's exactly one preamble record in sql. What I'm wondering is how many records we want in the document store that correspond to that single record in sql. For the `Regulation` model and `RegulationIndex` search index, the correspondence is one relational record to one document record, because regulations have one sql row per node. But preambles don't--all the nodes are stored in a big blob.

So, let me ask what I hope is a better question: do we want one document record for each preamble relational record, or one document record for each preamble node?

**Comment by cmc333333** [comment]
One record per preamble node

**Comment by cmc333333** [comment]
Note that doing

1) create a row per node (as we do with the CFR data)

collapses your question. One node <=> one db row <=> one indexed document

**Comment by jmcarp** [comment]
OK, so is this also meant to change the relational data model for preambles?

**Comment by cmc333333** [comment]
That'd be a clean approach, yep. If you want to do something else, go for it, but haystack works easiest with one document per model.

**Comment by cmc333333** [comment]
This has been all merged
