### ISSUE TITLE
Account for header padding in Preamble

### ISSUE THREAD

**Issue by cmc333333** [eregs/notice-and-comment#132]
Clicking on one of the ToC links, I see:
<img width="810" alt="screen shot 2016-04-12 at 10 23 35 am" src="https://cloud.githubusercontent.com/assets/326918/14463360/b53b1056-0098-11e6-8795-761d2d73e802.png">

Note that this is scrolled _down_ from where it's supposed to be:
<img width="658" alt="screen shot 2016-04-12 at 10 23 46 am" src="https://cloud.githubusercontent.com/assets/326918/14463382/c529f6f8-0098-11e6-8e81-f92b1b5f6039.png">

IIRC, there was some sort of padding or margin added to every paragraph to account for an offset caused by the header.

**Comment by xtine** [comment]
I've been trying to figure this out. There hasn't been any change in list style padding/margins (as far as I can tell, and even commenting out a padding change in my last PR didn't fix this), however maybe something with the TOC navigation has a little part in it, since if I click on "I. General Information" will take me to I#2016_02749-I-A instead of just I.

**Comment by donjo** [comment]
I think I changed something a few weeks ago when implementing the top nav
styling and logos/seals knowing that it would need to be looked at later
once we figured out what our content looked like. Since "later" has now
arrived, I'll look into it.

On Tue, Apr 12, 2016 at 12:31 PM, christine <notifications@github.com>
wrote:

> I've been trying to figure this out. There hasn't been any change in list
> style padding/margins (as far as I can tell, and even commenting out a
> padding change in my last PR didn't fix this), however maybe something with
> the TOC navigation has a little part in it, since if I click on "I. General
> Information" will take me to I#2016_02749-I-A instead of just I.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eregs/notice-and-comment/issues/132#issuecomment-209020003>
>



-- 
John Donmoyer
18F – User Experience Designer
312-869-0339

**Comment by cmc333333** [comment]
It's also very possible that this has never worked for the preamble + anchor combination; perhaps there's something in the regulation text stylesheets that resolves it which isn't being applied in the preamble.

**Comment by xtine** [comment]
I reverted to a branch from a week ago and it didn't have this issue, so I think it's just trying to narrow it down to something we pushed up last week or this weekend.

**Comment by cmc333333** [comment]
I believe this is related to `position: relative;`, which also prevents users from clicking or highlighting in the bottom portion of a paragraph in the CFR changes.
