### ISSUE TITLE
The user can see an excerpt of the section they are commenting on

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#202]
Write mode
[ALMOST] The user can see an excerpt of the section they are commenting on. [Some bugs between “write a comment” links vs tab]

**Comment by jehlers** [comment]
Related to #202

We want each excerpt to have a header that matches the section title the user will see when they save their comment and it is added to the right sidebar list of pending comments.

![screen shot 2016-04-25 at 11 05 29 am](https://cloud.githubusercontent.com/assets/4267825/14788411/b1948094-0ad5-11e6-94af-4302cf192eac.png)

**Comment by jehlers** [comment]
Here are some design directions for the excerpt on the page where the user is writing their comment. Our main goal is to provide context to the user to keep them on track and help them to write their most effective comment possible.

_(xposting from our team slack conversation)_

#### 1 - Incremental expansion

In this design, the excerpt is above the comment which is the intuitive place to put information you are writing about. Images in text books ​_usually_​ work this way, medium’s comments work this way, etc… One of our goals is to get better comments by keeping people on track, this design always has the content in the user’s line of sight as they are writing (or pasting) their comment. The show more could expand the whole section, or incrementally by a few lines at a time like the CFR changes.

![write mode 01 copy 10](https://cloud.githubusercontent.com/assets/4267825/15186369/cc3d9204-176a-11e6-9014-fde0ad99da44.png)

#### 2 - Section below the comment

This has the benefit of putting the comment box front and center. It allows us to show a whole excerpt w/o any kind of interaction to expand or scroll (once the user finds it). We have a link that points the user to the excerpt so they know it is there.

![write mode 01 copy 12](https://cloud.githubusercontent.com/assets/4267825/15186397/dee41478-176a-11e6-8809-43380b2c3357.png)

#### 3 - Scrolling

This is essentially what we have now. We haven’t seen any users be confused by this interaction yet (even without any design to indicate the scrolling interaction). I do like how the user can see everything but is still taken out of the read mode. Some of the other designs I do question if we need the excerpt at all. I can play with this design more if we do want to keep this. Not sure how well the scrolling indication is working.

Mobile is the big issue for this one. Since mobile has the read/write tabs so prominently close to the comment box, I’m wondering IF we need the excerpt at all on mobile.

![write mode 01 copy 13](https://cloud.githubusercontent.com/assets/4267825/15186413/f18059de-176a-11e6-8788-68ec381daf4e.png)

#### 4 - Do we need an excerpt at all?

The user can get back to the content in the read mode either through the internal link above, or by clicking the write mode tab OR the TOC. If the excerpt is cluttering this page, should we hide it on default? This example gives the user the opportunity to expand the excerpt here IF they want to see it. But keeps the page clean if they don’t want it.

![write mode 01 copy 14](https://cloud.githubusercontent.com/assets/4267825/15186433/fff8df9a-176a-11e6-807e-06e177f9ad3f.png)

**Comment by jehlers** [comment]
After a great discussion in slack, the team is leaning towards option 4 above. But, option 4 will expand to show option 3. This meets our goals in the middle - bringing the comment box closer to the "write your comment" call to action, but still allowing users to see context if they need it. 

We also discussed the benefits/disadvantages of the tabs. There is a potential future where we try without the tabs and bring the "Your comment" sidebar into read mode. This is something we plan to focus on during our open comment period research. 😄 

#### Closed excerpt

![write mode 01 copy 14](https://cloud.githubusercontent.com/assets/4267825/15188048/cb2b3a18-1771-11e6-8233-76502d2a12e3.png)

#### Open excerpt

![write mode 01 copy 15](https://cloud.githubusercontent.com/assets/4267825/15188052/d336cc68-1771-11e6-826f-615f50bb5cbe.png)

**Comment by jehlers** [comment]
Additional thoughts to play with - should there be more explicit headers between "this is what you're commenting on" and "you are writing a comment here"?

**Comment by jehlers** [comment]
Most recent update - taking away the main "compose your comment" header in favor of having the three main headers explain each part of the page. 

![write mode 01 copy 20](https://cloud.githubusercontent.com/assets/4267825/15216726/50bb12de-1826-11e6-919d-9c80bfae593c.png)

**Comment by cmc333333** [comment]
@xtine got this with eregs/regulations-site#380
