### ISSUE TITLE
Message when the tracking number cannot be obtained because we could not submit to regs.gov

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#214]
[NEEDED] Message when the tracking number cannot be obtained because we could not submit to regs.gov.

**Comment by vrajmohan** [comment]
When the submission to regs.gov fails, we retry it up to 3 times, 3 minutes apart (all of which can be configured). If we have exceeded the maximum retries, we save the submission in eregs, for later _manual_ submission to regs.gov. This can live in the same spot as *Success* and say something like:
"Although we can't give you a tracking number, your submission is in our safe hands and will make it to regs.gov. You can search for it later using keyword searches."

**Comment by jehlers** [comment]
Ok! Taking a look at this now. To clarify, the user will have been looking at this confirmation screen for somewhere around 9 minutes before the new message will appear and replace the blue box area. Is that correct?

<img width="742" alt="screen shot 2016-05-17 at 12 24 19 pm" src="https://cloud.githubusercontent.com/assets/4267825/15330329/728df6bc-1c2a-11e6-9941-69f4dc1cb357.png">

**Comment by cmc333333** [comment]
Mostly! After nine (possibly more, depending on load) minutes of trying, we'll know that we gave up on sending the comment automatically. It then gets added to a collection which we'll need to submit through a different route.

To answer your specific question, yes the user will be on this screen. But we _know_ that waiting any longer won't help, so we should probably remove that text at this point. Does that make sense?

**Comment by jehlers** [comment]
Yes. I _think_ we're on the same 📄. Will upload some designs shortly.

**Comment by jehlers** [comment]
Here are a few options:

#### Option 1

Replacing the text in the blue message with a new message. 

<img width="578" alt="screen shot 2016-05-17 at 2 19 23 pm" src="https://cloud.githubusercontent.com/assets/4267825/15334341/c3907e02-1c3b-11e6-8dfe-6200ae2f36c6.png">

#### Option 2 

Similar to option 1 but using the same 2 message alert as what would have already been on the page.

<img width="590" alt="screen shot 2016-05-17 at 2 22 14 pm" src="https://cloud.githubusercontent.com/assets/4267825/15334352/d0c6f3bc-1c3b-11e6-812e-3ab68a63f22a.png">

#### Option 3

Replacing more words.

<img width="587" alt="screen shot 2016-05-17 at 2 28 57 pm" src="https://cloud.githubusercontent.com/assets/4267825/15334402/032b13ec-1c3c-11e6-9d1c-1bfb726611ab.png">

**Comment by cmc333333** [comment]
I like option 2. Less wordy that option 1, but still highlighting the explanation (I'd not read the explanation in option 3).

**Comment by brittag** [comment]
Oh cool! I like the design of option 2 - it makes sense to me that the explanation should be visually part of the warning/caution note, and the little "i" helps indicate that the second part is a tip/guidance.

Thoughts on content:

"This page automatically displays that comment tracking number when received" could be more informative if we explain who (or what) is receiving it, something like this: "This page automatically displays that comment tracking number when we receive it."

Then that could help people understand what we mean by "Sorry, we did not receive your comment tracking number."

In the explanatory text, can we more explicitly say "We sent your comment to EPA, and they will assign it a tracking number" - since it's possible to read "Your comment is still being sent to EPA" as "it's not there yet - it's still in transit somewhere and might get lost". Can we also briefly explain a typical reason why we might not have received the tracking number, as further reassurance? (Such as "their system may be busy at the moment.")

Do we need to be cautious about saying "a few days" rather than being more vague?

Putting this all together, a suggestion (feel free to use or discard):

> **Your comment tracking number**

> The first step EPA takes is to assign your comment a tracking number. This page automatically displays that number when we receive it:

> [ ! ] **Sorry, we did not receive your comment tracking number.**

> [ i ] This does not affect your comment. We sent your comment to EPA, and they will process it (their system may be busy at the moment). You will be able to find your comment using keyword searches after they process it, usually a few days.

**Comment by vrajmohan** [comment]
"We did not receive your tracking number" sounds like we sent it to the EPA docket, but were unable to get tracking number. @brittag's comments confirm that interpretation. I would rather go with the truth, which is "We were unable to send it to the EPA docket".

**Comment by brittag** [comment]
Ah good point, yes! It'd be nice to explain that we were unable to send it and what we are doing instead.

**Comment by vrajmohan** [comment]
Also, to make it less onerous for the user, would we prefer a timeout <9m? As @cmc333333 explained, 9m comes from _Celery's_ default settings - we make 3 attempts 3m apart.

**Comment by cmc333333** [comment]
There's a balance to be struck around how often to try submitting the data. If we think that submissions will fail _consistently_, we don't really need to retry. If we think the failures are _temporary_, retrying multiple times over a long period would be best (in this case optimizing for more automation and fewer manual submissions). I don't feel confident that we have a good idea of where that balance is, so I'd recommend using the defaults. I'd also recommend we don't spend too much time thinking about this -- we're expecting it to be an odd corner case.

Somewhat related: we can't promise under 9 minutes as it depends on our load, too.

**Comment by jehlers** [comment]
9 minutes seems like a reasonable timebox to me. I really don't think people will be still waiting with bated breath at that point, so no need to wait longer if we're sure at that point that we need to send their comments in another way.

@vrajmohan "We were unable to send it to the EPA docket," but we will right? That's what I want use to be able to say. I see the confusion with "receive" though.

What about something like this:

> [ ! ] Sorry, we were note able to send your comment to the EPA docket at this time.
>
> [ i ] This does not affect your comment! We will send your comment to EPA, and they will process it (their system may be busy at the moment). You will be able to find your comment using keyword searches after they process it, usually a few days.

The issue here is it sounds more worrying than just not receiving a tracking number.. @brittag do you have any better ideas of how to say this? (Also sorry! I know you're busy!)

Also, we can figure out the few days part. Or we could take it out and just end the sentence with "after they process it." ?

**Comment by cmc333333** [comment]
Swapping out "to EPA" with "to the agency" to be more general purpose.
