### ISSUE TITLE
Design for the homepage

### ISSUE THREAD

**Issue by Journerdism** [eregs/notice-and-comment#218]
[Almost] Design for the homepage

**Comment by jehlers** [comment]
Started in #58

**Comment by jehlers** [comment]
Current design:

![homepage 8675309 copy 3](https://cloud.githubusercontent.com/assets/4267825/14829279/843e44ac-0bb8-11e6-930f-729c1c7abd4b.png)

**Comment by jehlers** [comment]
Switching up the color backgrounds to make it a little easier to read. Otherwise, I think the design is in a good place now. We can play with the photo a little as we run into issues with implementation.

![homepage](https://cloud.githubusercontent.com/assets/4267825/14924872/87722bdc-0e12-11e6-9cce-b9d9b82dabb5.png)

cc @xtine
