### ISSUE TITLE
Handle worker interruptions

### ISSUE THREAD

**Issue by jmcarp** [eregs/notice-and-comment#30]
Celery attempts to stop workers gracefully, so that pending tasks are sent back to the broker to be rescheduled. But if the worker is stopped before it has time to notify the broker, tasks can be lost.

This behavior can be avoided using the `acks_late` option, so that tasks aren't popped from the broker until the worker notifies that they have been completed, but this setting can also cause problems if tasks aren't idempotent. Unfortunately, comment submission is *not* idempotent--if a worker is ungracefully stopped between submitting a comment to regs.gov and sending the late ack to the broker, the comment will be submitted again.

If comments can be de-duplicated (perhaps by a unique key that we set) on regs.gov, then I think we can safely use the `acks_late` flag. Otherwise, I'm not sure what the best option is. Note that this is a problem that needs to be addressed for any task queue, since comment submission isn't atomic (we can't reliably roll it back if a later step in the task fails).

Flagging @cmc333333 and @vrajmohan for feedback. My initial thought is that `acks_late` combined with de-duplication on regs.gov would handle this well, but I'm not sure whether the second part is an option.

**Comment by jmcarp** [comment]
Helpful docs at http://celery.readthedocs.org/en/latest/faq.html#should-i-use-retry-or-acks-late and https://devcenter.heroku.com/articles/celery-heroku.

**Comment by cmc333333** [comment]
Looks like you've stumbled upon a distributed system! My condolences.

Question on `acks_late`: if you have multiple worker processes, is there some sort of a timeout before the next worker tries to accept that message? Otherwise, we'll need a mutex... and we're back to implementing a lot of this ourselves :/

Regs.gov gives us a submission id, but only at the end of this process; further, we can't query it immediately. If I understand your suggestion correctly, we could build something like this:

id | created_at | submitted_at | submission_id
---|---|---|---
processed-uuid | [timestamp] | [timestamp] | regs.gov id
unprocessed-uuid | [timestamp] | null | null

Is that what you're imagining?

A few notes:
* Again, I don't like needing to manage this ourselves, but if there's not a solution provided by Celery, we may have to.
* The submission id from regs.gov isn't really necessary here (we can rely on `submitted_at`); it is however useful for follow up
* This doesn't avoid certain race conditions. That said, I'm not sure it's possible to build a distributed commit in this scenario; here, it makes more sense to lean towards submitting a comment multiple times than never.

**Comment by jmcarp** [comment]
> Question on acks_late: if you have multiple worker processes, is there some sort of a timeout before the next worker tries to accept that message?

Yes--the timeout defaults to an hour, but can be customized like so: http://docs.celeryproject.org/en/latest/getting-started/brokers/redis.html#visibility-timeout

> That said, I'm not sure it's possible to build a distributed commit in this scenario; here, it makes more sense to lean towards submitting a comment multiple times than never.

Exactly--since we have at least one action (comment submission) that we can't roll back (as far as I know), I don't know that we can have commits here.

What I'm suggesting isn't even as sophisticated as tracking submission timestamps or IDs, since it's possible for the worker to crash between successfully submitting a comment and storing the submission ID. What I'm naively suggesting is that we either (1) simply allow for the (rare) possibility of duplicate submissions and trust regs.gov to ignore extras or (2) generate a unique and predictable submission ID to help regs.gov detect potential duplicates. Those two proposals are exactly the same, other than potentially giving regs.gov content hash so they wouldn't have to compute it themselves.

The situation in which we run into problems (a worker crashes or is shut down ungracefully) is rare, and there may be steps we can take to make it extremely rare. As far as I can tell from the docs (haven't dug into the source yet), celery workers will stop accepting new tasks but attempt to finish pending tasks when they're stopped using `SIGTERM`. If we can configure cloud.gov to use an adequate delay between `SIGTERM` and `SIGKILL`, we can decrease the chance that pending tasks get killed. And if submitting the comment is the last action in the task (which it is now), the window of duplicate submissions--which happen when the worker is killed between submitting the comment and sending the `ACK`--is very small.

**Comment by jmcarp** [comment]
Basically, my suggestion here is to use `acks_late`, with a very small risk of duplicate submissions. Thoughts @cmc333333 @vrajmohan?

**Comment by vrajmohan** [comment]
I am OK with `acks_late`, with a very small risk of duplicate submissions. Sorry to conflate issues, but my worry is more about the dropping of failed tasks after max retries. If we do use Rabbit, I am at a loss to see what Celery is providing to the stack.
