### ISSUE TITLE
Preamble introduction polish

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#357]
**HIGHEST PRIORITY**
- [ ] "AGENCY, ACTION, etc..." headers are all H4 right now. Can they be styled like an H3 instead (since the title above them is styled as an H2)? That way also the "Supporting documents from the docket:" will match. 
  - [ ] Similarly... H3 in the rest of the tool have more space above each header to space the paragraphs out a little more. Can we bring that space into this page? Its feeling a little cluttered right now.
  - [x] IF we have to keep the all caps for these headers for data reasons, can we match "Supporting documents from the docket:" so that it feels like its a part of this section and not randomly different?
- [x] "Rule published on May X, 2016" should be 16px Source Sans Pro Regular
- [ ] Can we add the link "View regulatory contacts" next to the supporting docs link? It can link down to: "FOR FURTHER INFORMATION CONTACT:"?
- [x] Can we have 45px of visual space above and below the stroke?

**MEDIUM**
- [x] If/when the "Comment period closes on September 1, 2016 at 11:59pm EST." goes onto a second line, can we still vertically center it with the days counter? So then it would line up with the top of that box?
  - [x] On mobile, we want to hide the countdown box.
- [x] Can the stroke be #D6D7D9

**LOW**
- [x] "DAYS" is it 14px? If not, can it be 14px and Semibold?

cc @xtine and @donjo

**Comment by donjo** [comment]
Right now we had to punt on linking to the contact part of the preamble introduction because we don't have a good identifier for that information right now. In the future we'll look to add logic to pull it out more cleanly. 

([Slack discussion for reference](https://18f.slack.com/archives/eregs-notice/p1464985957002146))

I'll leave the mobile countdown box out for now until I see what @xtine does in the larger mobile-ready pull request. 

The headers are all being pulled in the way they are due to the document structure right now. I temporarily did the fallback option but I may have an idea on how to address that they way you are talking about but it may not be a good idea. Will report back.

**Comment by donjo** [comment]
Done aside from the part about the headers being in ALL CAPS. That's how they are in the document right now.
