### ISSUE TITLE
Write mode polish

### ISSUE THREAD

**Issue by jehlers** [eregs/notice-and-comment#68]
- What should the excerpt look like?
- Should the colors of the right comment boxes match the TOC and other things?
- Should we add the remove option to the current comment?
- Should save be "Add to comment" or something else?
- Etc...

![screen shot 2016-03-25 at 5 19 21 pm](https://cloud.githubusercontent.com/assets/4267825/14054189/b02fd90a-f2ad-11e5-9d58-eea271abefe4.png)

**Comment by xtine** [comment]
Account for different states in Write mode:
* What does it show when there are no pending comments on the right sidebar?
* Save errors: attachment too big, unsupported attachment type, character limit, server error

**Comment by xtine** [comment]
Attachment states:
* Default state, no attachments
* User is attaching a file (maybe a progress bar or message that attachment is uploading, related to interface for #37)
* Listing of attachments (perhaps with ability to delete an attachment with "x" icon next to an attachment?)
* Error/warning - attachment too large, unsupported type, cannot upload any more attachments

**Comment by xtine** [comment]
There's also an edge case possibility of when a user is attempting to make comments that exceed the max limit either by word count or file size if we are generating a PDF stitching together total comments Would we attempt to prevent the user from writing another comment once they have reached the limit ("you have entered too many characters"), or perhaps there be some status on the right sidebar that says "you have X characters left, you have X number of attachments left, etc).

Otherwise, if they try to submit too much the warning would come from an error when they try to submit their final comments at the end of the review page.

**Comment by jehlers** [comment]
That's interesting @xtine! Maybe that can go somewhere like with the "you have X pending comments" text.

**Comment by donjo** [comment]
Splitting this up into some smaller chunks:

#136 
#37 
#137
#138
#139
